const BREWERY_DB_API_KEY = "";
const UNTAPPD_CLIENT_SECRET_IOS = "";
const UNTAPPD_CLIENT_ID_IOS = "";
const UNTAPPD_CLIENT_SECRET_ANDROID = "";
const UNTAPPD_CLIENT_ID_ANDROID = "";
const SENTRY_DSN = "";